import { runImagePlanTests } from "./imagePlan.test";
import { runPlaceholderTests } from "./placeholders.test";
import { runLlmParsingTests } from "./llmParsing.test";
import { runLlmBatchingTests } from "./llmBatching.test";
import { runQualityGateTests } from "./qualityGate.test";
import { runTemplateGeneratorTests } from "./templateGenerator.test";
import { runLayoutSelectorTests } from "./layoutSelector.test";
import { runLayoutCompilerTests } from "./layoutCompiler.test";
import { runTemplateGenerateArgTests } from "./templateGenerateArgs.test";
import { runLayoutsSelectorTests } from "./layoutsSelector.test";
import { runLayoutsBinderTests } from "./layoutsBinder.test";
import { runLayoutsImportTests } from "./layoutsImport.test";
import { runLayoutsMergeTests } from "./layoutsMerge.test";
import { runLayoutsCompilerTests } from "./layoutsCompiler.test";
import { runLayoutsWorkerSmokeTests } from "./layoutsWorkerSmoke.test";
import { runRagRetrieveTests } from "./ragRetrieve.test";
import { runThemeStoreTests } from "./themeStore.test";
import { runContentQaTests } from "./contentQa.test";
import { runPlanImageReplacementsTests } from "./planImageReplacements.test";
import { runNarrativePlanTests } from "./narrativePlan.test";
import { runDeckPlanTests } from "./deckPlan.test";
import { runThemeQaTests } from "./themeQa.test";
import { runSchemaTests } from "./schema.test";
import { runContentRepairTests } from "./contentRepair.test";
import { runContentAwareLayoutTests } from "./contentAwareLayout.test";
import { runLayoutVisualRegressionTests } from "./layoutVisualRegression.test";
import { runObservabilityTests } from "./observability.test";
import { runP1RegressionCorpusTests } from "./p1RegressionCorpus.test";

const run = async (): Promise<void> => {
  runPlaceholderTests();
  runThemeStoreTests();
  runThemeQaTests();
  runSchemaTests();
  runObservabilityTests();
  runP1RegressionCorpusTests();
  runContentQaTests();
  runContentRepairTests();
  runContentAwareLayoutTests();
  await runLayoutVisualRegressionTests();
  runNarrativePlanTests();
  await runDeckPlanTests();
  runImagePlanTests();
  await runPlanImageReplacementsTests();
  runLlmParsingTests();
  runLlmBatchingTests();
  runQualityGateTests();
  runTemplateGeneratorTests();
  runLayoutSelectorTests();
  runLayoutCompilerTests();
  runTemplateGenerateArgTests();
  runLayoutsSelectorTests();
  runLayoutsBinderTests();
  runLayoutsImportTests();
  await runLayoutsMergeTests();
  await runLayoutsCompilerTests();
  await runLayoutsWorkerSmokeTests();
  runRagRetrieveTests();
  console.log("tests: ok");
};

void run();
